services:
    db:
        image: mysql/mysql-server:8.0.28
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: recipes
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
        cap_add:
            - SYS_NICE
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - db:/var/lib/mysql
            - ./config/create-databases.sql:/docker-entrypoint-initdb.d/create-databases.sql
volumes:
    db:
