CREATE DATABASE IF NOT EXISTS recipes DEFAULT CHARACTER SET = utf8;
CREATE DATABASE IF NOT EXISTS recipes_testing DEFAULT CHARACTER SET = utf8;
GRANT ALL PRIVILEGES ON recipes.* TO 'admin'@'%';
GRANT ALL PRIVILEGES ON recipes_testing.* TO 'admin'@'%';
FLUSH PRIVILEGES;
